name: kernel
dependencies:
  # We import some of the analyzer's internal files, so lock the patch version.
  analyzer: 0.28.1
  path: ^1.3.9
  args: ^0.13.4
  logging: ^0.11.2
dev_dependencies:
  test: ^0.12.13
  stack_trace: ^1.6.6
  testing:
    git:
      url: https://github.com/peter-ahe-google/testing.git
      ref: dd8271d
